name: pochi
description: "Let's おさんぽ"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  google_fonts: ^6.3.1
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_config:
    git:
      url: https://github.com/dev-mahmoud-elshenawy/flutter_config-flutter3.29.0-fix
      ref: master
  google_maps_flutter: ^2.12.3
  flutter_overpass: ^1.2.0
  bottom_sheet_bar: ^2.3.11
  http: ^1.5.0
  flutter_polyline_points: ^3.0.1
  flutter_google_map_polyline_point: ^0.0.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/1.mp3
    - assets/cute_button.mp3